### ISSUE TITLE
[Refactor/#31] API 서버 Producer, Consumer 추상화 - [merged]

### ISSUE THREAD

**Issue by TaeyeongKwak** [G-GCELL/api-server#82]
In GitLab by @muyongKim on Feb 15, 2023, 17:50

_Merges refactor/#31 -> dev_

## 📋 구현 내용

> Producer, Consumer를 인터페이스로 추상화

- Producer, Consumer 인터페이스 생성
- Producer, Consumer 구현 클래스 생성
- Producer, Consumer, DTO 클래스 네이밍 통일

## 🔍 테스트 케이스
- 없음

## 📢 코멘트
환경변수가 아래처럼 수정되었습니다.

```
rabbitmq:
  direct-exchange: ${DIRECT_EXCHANGE}
  file-create-progress-exchange: ${FILE_CREATE_PROGRESS_EXCHANGE}
  file-create-request-queue: ${FILE_CREATE_REQUEST_QUEUE}
  file-create-request-routing-key: ${FILE_CREATE_REQUEST_ROUTING_KEY}
```

@tommysgit @AnTaeWook @TaeYeongKwak
