### ISSUE TITLE
[Refactor/#35] API 서버 RabbitMQ property 수정 - [merged]

### ISSUE THREAD

**Issue by TaeyeongKwak** [G-GCELL/api-server#85]
In GitLab by @muyongKim on Feb 20, 2023, 11:23

_Merges refactor/#35 -> dev_

## 📋 구현 내용

> RabbitMQ property를 구분할 수 있도록 수정하고 이를 `RabbitmqConfigProperty` Inner class로 매핑

- 설정 파일 RabbitMQ property 수정
- `RabbitmqConfigProperty` Inner class 구현

## 🔍 테스트 케이스
- 없음

## 📢 코멘트
- **현재 RabbitMQ 관련 환경변수입니다**. 해당 값 세팅하실 때 문제가 발생하면 바로 말씀해주세요.
  ```
  rabbitmq:
  host: ${RABBITMQ_HOST}
  port: ${RABBITMQ_PORT}
  username: ${RABBITMQ_USER}
  password: ${RABBITMQ_PASSWORD}
  exchange:
    direct-exchange: ${DIRECT_EXCHANGE}
    file-create-progress-exchange: ${FILE_CREATE_PROGRESS_EXCHANGE}
  queue:
    file-create-request-queue: ${FILE_CREATE_REQUEST_QUEUE}
    file-create-progress-queue: ${FILE_CREATE_PROGRESS_QUEUE}
  routing-key:
    file-create-request-routing-key: ${FILE_CREATE_REQUEST_ROUTING_KEY}
  ```

@tommysgit @AnTaeWook @TaeYeongKwak
